import { PujaCategory, PujaService, Package } from './types';

export const mockCategories: PujaCategory[] = [
  { id: 1, name: 'Ganesha Puja', created_at: '2024-01-01', updated_at: '2024-01-01' },
  { id: 2, name: 'Lakshmi Puja', created_at: '2024-01-01', updated_at: '2024-01-01' },
  { id: 3, name: 'Saraswati Puja', created_at: '2024-01-01', updated_at: '2024-01-01' },
  { id: 4, name: 'Shiva Puja', created_at: '2024-01-01', updated_at: '2024-01-01' },
  { id: 5, name: 'Durga Puja', created_at: '2024-01-01', updated_at: '2024-01-01' },
  { id: 6, name: 'Navgraha Puja', created_at: '2024-01-01', updated_at: '2024-01-01' },
  { id: 7, name: 'Satyanarayan Puja', created_at: '2024-01-01', updated_at: '2024-01-01' },
  { id: 8, name: 'Griha Pravesh Puja', created_at: '2024-01-01', updated_at: '2024-01-01' },
];

export const mockPackages: Package[] = [
  // Ganesha Puja packages
  {
    id: 1,
    puja_service: 1,
    location: 'Mumbai',
    language: 'HINDI',
    package_type: 'BASIC',
    price: '2500.00',
    description: 'Basic Ganesha Puja with essential rituals, simple offerings, and basic pooja items',
    includes_materials: false,
    priest_count: 1,
    is_active: true,
    created_at: '2024-01-01',
    updated_at: '2024-01-01'
  },
  {
    id: 2,
    puja_service: 1,
    location: 'Mumbai',
    language: 'HINDI',
    package_type: 'STANDARD',
    price: '4500.00',
    description: 'Standard Ganesha Puja with enhanced rituals, quality offerings, and premium pooja items',
    includes_materials: true,
    priest_count: 1,
    is_active: true,
    created_at: '2024-01-01',
    updated_at: '2024-01-01'
  },
  {
    id: 3,
    puja_service: 1,
    location: 'Mumbai',
    language: 'SANSKRIT',
    package_type: 'PREMIUM',
    price: '7500.00',
    description: 'Premium Ganesha Puja with elaborate rituals, luxury offerings, and complete pooja setup',
    includes_materials: true,
    priest_count: 2,
    is_active: true,
    created_at: '2024-01-01',
    updated_at: '2024-01-01'
  },
  
  // Lakshmi Puja packages
  {
    id: 4,
    puja_service: 2,
    location: 'Delhi',
    language: 'HINDI',
    package_type: 'BASIC',
    price: '3000.00',
    description: 'Basic Lakshmi Puja for wealth and prosperity with essential rituals',
    includes_materials: false,
    priest_count: 1,
    is_active: true,
    created_at: '2024-01-01',
    updated_at: '2024-01-01'
  },
  {
    id: 5,
    puja_service: 2,
    location: 'Delhi',
    language: 'SANSKRIT',
    package_type: 'STANDARD',
    price: '5000.00',
    description: 'Standard Lakshmi Puja with enhanced rituals and quality materials',
    includes_materials: true,
    priest_count: 1,
    is_active: true,
    created_at: '2024-01-01',
    updated_at: '2024-01-01'
  },
  {
    id: 6,
    puja_service: 2,
    location: 'Delhi',
    language: 'SANSKRIT',
    package_type: 'PREMIUM',
    price: '8500.00',
    description: 'Premium Lakshmi Puja with elaborate rituals, gold offerings, and luxury setup',
    includes_materials: true,
    priest_count: 2,
    is_active: true,
    created_at: '2024-01-01',
    updated_at: '2024-01-01'
  },

  // Saraswati Puja packages
  {
    id: 7,
    puja_service: 3,
    location: 'Bangalore',
    language: 'HINDI',
    package_type: 'BASIC',
    price: '2000.00',
    description: 'Basic Saraswati Puja for knowledge and wisdom with essential mantras',
    includes_materials: false,
    priest_count: 1,
    is_active: true,
    created_at: '2024-01-01',
    updated_at: '2024-01-01'
  },
  {
    id: 8,
    puja_service: 3,
    location: 'Bangalore',
    language: 'SANSKRIT',
    package_type: 'STANDARD',
    price: '3500.00',
    description: 'Standard Saraswati Puja with enhanced learning rituals and quality materials',
    includes_materials: true,
    priest_count: 1,
    is_active: true,
    created_at: '2024-01-01',
    updated_at: '2024-01-01'
  },
  {
    id: 9,
    puja_service: 3,
    location: 'Bangalore',
    language: 'SANSKRIT',
    package_type: 'PREMIUM',
    price: '6000.00',
    description: 'Premium Saraswati Puja with elaborate learning rituals and complete setup',
    includes_materials: true,
    priest_count: 2,
    is_active: true,
    created_at: '2024-01-01',
    updated_at: '2024-01-01'
  },

  // Mahamrityunjaya Puja packages
  {
    id: 10,
    puja_service: 4,
    location: 'Chennai',
    language: 'SANSKRIT',
    package_type: 'BASIC',
    price: '4000.00',
    description: 'Basic Mahamrityunjaya Puja for health and protection with essential mantras',
    includes_materials: false,
    priest_count: 1,
    is_active: true,
    created_at: '2024-01-01',
    updated_at: '2024-01-01'
  },
  {
    id: 11,
    puja_service: 4,
    location: 'Chennai',
    language: 'SANSKRIT',
    package_type: 'STANDARD',
    price: '6500.00',
    description: 'Standard Mahamrityunjaya Puja with enhanced healing rituals and quality materials',
    includes_materials: true,
    priest_count: 1,
    is_active: true,
    created_at: '2024-01-01',
    updated_at: '2024-01-01'
  },
  {
    id: 12,
    puja_service: 4,
    location: 'Chennai',
    language: 'SANSKRIT',
    package_type: 'PREMIUM',
    price: '10000.00',
    description: 'Premium Mahamrityunjaya Puja with elaborate healing rituals, 108 recitations, and complete setup',
    includes_materials: true,
    priest_count: 2,
    is_active: true,
    created_at: '2024-01-01',
    updated_at: '2024-01-01'
  },

  // Additional packages for other services (continuing with similar pattern)
  // Durga Puja packages
  {
    id: 13,
    puja_service: 5,
    location: 'Kolkata',
    language: 'HINDI',
    package_type: 'BASIC',
    price: '5000.00',
    description: 'Basic Durga Puja for divine protection with essential rituals',
    includes_materials: false,
    priest_count: 1,
    is_active: true,
    created_at: '2024-01-01',
    updated_at: '2024-01-01'
  },
  {
    id: 14,
    puja_service: 5,
    location: 'Kolkata',
    language: 'SANSKRIT',
    package_type: 'STANDARD',
    price: '8000.00',
    description: 'Standard Durga Puja with enhanced protection rituals and quality materials',
    includes_materials: true,
    priest_count: 2,
    is_active: true,
    created_at: '2024-01-01',
    updated_at: '2024-01-01'
  },
  {
    id: 15,
    puja_service: 5,
    location: 'Kolkata',
    language: 'SANSKRIT',
    package_type: 'PREMIUM',
    price: '12000.00',
    description: 'Premium Durga Puja with elaborate protection rituals, multiple offerings, and complete setup',
    includes_materials: true,
    priest_count: 3,
    is_active: true,
    created_at: '2024-01-01',
    updated_at: '2024-01-01'
  },

  // Navgraha Puja packages  
  {
    id: 16,
    puja_service: 6,
    location: 'Pune',
    language: 'SANSKRIT',
    package_type: 'BASIC',
    price: '6000.00',
    description: 'Basic Navgraha Puja for planetary peace with essential planetary mantras',
    includes_materials: false,
    priest_count: 1,
    is_active: true,
    created_at: '2024-01-01',
    updated_at: '2024-01-01'
  },
  {
    id: 17,
    puja_service: 6,
    location: 'Pune',
    language: 'SANSKRIT',
    package_type: 'STANDARD',
    price: '9000.00',
    description: 'Standard Navgraha Puja with enhanced planetary rituals and quality materials',
    includes_materials: true,
    priest_count: 1,
    is_active: true,
    created_at: '2024-01-01',
    updated_at: '2024-01-01'
  },
  {
    id: 18,
    puja_service: 6,
    location: 'Pune',
    language: 'SANSKRIT',
    package_type: 'PREMIUM',
    price: '15000.00',
    description: 'Premium Navgraha Puja with elaborate planetary rituals, gemstone offerings, and complete setup',
    includes_materials: true,
    priest_count: 2,
    is_active: true,
    created_at: '2024-01-01',
    updated_at: '2024-01-01'
  },

  // Adding packages for services 8-24
  // Griha Pravesh Puja packages (Service 8)
  {
    id: 22,
    puja_service: 8,
    location: 'All Cities',
    language: 'HINDI',
    package_type: 'BASIC',
    price: '4000.00',
    description: 'Basic Griha Pravesh with essential purification rituals and basic materials',
    includes_materials: false,
    priest_count: 1,
    is_active: true,
    created_at: '2024-01-01',
    updated_at: '2024-01-01'
  },
  {
    id: 23,
    puja_service: 8,
    location: 'All Cities',
    language: 'SANSKRIT',
    package_type: 'STANDARD',
    price: '6500.00',
    description: 'Standard Griha Pravesh with enhanced rituals, Vastu correction, and quality materials',
    includes_materials: true,
    priest_count: 1,
    is_active: true,
    created_at: '2024-01-01',
    updated_at: '2024-01-01'
  },
  {
    id: 24,
    puja_service: 8,
    location: 'All Cities',
    language: 'SANSKRIT',
    package_type: 'PREMIUM',
    price: '10000.00',
    description: 'Premium Griha Pravesh with elaborate Vastu rituals, multiple deity worship, and complete setup',
    includes_materials: true,
    priest_count: 2,
    is_active: true,
    created_at: '2024-01-01',
    updated_at: '2024-01-01'
  },

  // Kaal Sarp Dosh Puja packages (Service 9)
  {
    id: 25,
    puja_service: 9,
    location: 'Ujjain',
    language: 'SANSKRIT',
    package_type: 'BASIC',
    price: '8000.00',
    description: 'Basic Kaal Sarp Dosh Puja with essential mantras and basic offerings',
    includes_materials: false,
    priest_count: 1,
    is_active: true,
    created_at: '2024-01-01',
    updated_at: '2024-01-01'
  },
  {
    id: 26,
    puja_service: 9,
    location: 'Ujjain',
    language: 'SANSKRIT',
    package_type: 'STANDARD',
    price: '12000.00',
    description: 'Standard Kaal Sarp Dosh Puja with enhanced remedial rituals and quality materials',
    includes_materials: true,
    priest_count: 2,
    is_active: true,
    created_at: '2024-01-01',
    updated_at: '2024-01-01'
  },
  {
    id: 27,
    puja_service: 9,
    location: 'Ujjain',
    language: 'SANSKRIT',
    package_type: 'PREMIUM',
    price: '20000.00',
    description: 'Premium Kaal Sarp Dosh Puja with elaborate remedial rituals, multiple offerings, and complete setup',
    includes_materials: true,
    priest_count: 3,
    is_active: true,
    created_at: '2024-01-01',
    updated_at: '2024-01-01'
  },

  // Rudrabhishek Puja packages (Service 10)
  {
    id: 28,
    puja_service: 10,
    location: 'Varanasi',
    language: 'SANSKRIT',
    package_type: 'BASIC',
    price: '3500.00',
    description: 'Basic Rudrabhishek with essential Shiva mantras and simple offerings',
    includes_materials: false,
    priest_count: 1,
    is_active: true,
    created_at: '2024-01-01',
    updated_at: '2024-01-01'
  },
  {
    id: 29,
    puja_service: 10,
    location: 'Varanasi',
    language: 'SANSKRIT',
    package_type: 'STANDARD',
    price: '5500.00',
    description: 'Standard Rudrabhishek with enhanced Shiva worship and quality abhishek materials',
    includes_materials: true,
    priest_count: 1,
    is_active: true,
    created_at: '2024-01-01',
    updated_at: '2024-01-01'
  },
  {
    id: 30,
    puja_service: 10,
    location: 'Varanasi',
    language: 'SANSKRIT',
    package_type: 'PREMIUM',
    price: '9000.00',
    description: 'Premium Rudrabhishek with elaborate Shiva worship, precious offerings, and complete setup',
    includes_materials: true,
    priest_count: 2,
    is_active: true,
    created_at: '2024-01-01',
    updated_at: '2024-01-01'
  },

  // Hanuman Puja packages (Service 11)
  {
    id: 31,
    puja_service: 11,
    location: 'Delhi',
    language: 'HINDI',
    package_type: 'BASIC',
    price: '2000.00',
    description: 'Basic Hanuman Puja with essential mantras and simple prasadam',
    includes_materials: false,
    priest_count: 1,
    is_active: true,
    created_at: '2024-01-01',
    updated_at: '2024-01-01'
  },
  {
    id: 32,
    puja_service: 11,
    location: 'Delhi',
    language: 'HINDI',
    package_type: 'STANDARD',
    price: '3500.00',
    description: 'Standard Hanuman Puja with enhanced strength rituals and quality offerings',
    includes_materials: true,
    priest_count: 1,
    is_active: true,
    created_at: '2024-01-01',
    updated_at: '2024-01-01'
  },
  {
    id: 33,
    puja_service: 11,
    location: 'Delhi',
    language: 'SANSKRIT',
    package_type: 'PREMIUM',
    price: '6000.00',
    description: 'Premium Hanuman Puja with elaborate strength rituals, special offerings, and complete setup',
    includes_materials: true,
    priest_count: 2,
    is_active: true,
    created_at: '2024-01-01',
    updated_at: '2024-01-01'
  },

  // Dhanvantari Puja packages (Service 12)
  {
    id: 34,
    puja_service: 12,
    location: 'Chennai',
    language: 'SANSKRIT',
    package_type: 'BASIC',
    price: '4500.00',
    description: 'Basic Dhanvantari Puja with essential healing mantras and herbal offerings',
    includes_materials: false,
    priest_count: 1,
    is_active: true,
    created_at: '2024-01-01',
    updated_at: '2024-01-01'
  },
  {
    id: 35,
    puja_service: 12,
    location: 'Chennai',
    language: 'SANSKRIT',
    package_type: 'STANDARD',
    price: '7000.00',
    description: 'Standard Dhanvantari Puja with enhanced healing rituals and medicinal herbs',
    includes_materials: true,
    priest_count: 1,
    is_active: true,
    created_at: '2024-01-01',
    updated_at: '2024-01-01'
  },
  {
    id: 36,
    puja_service: 12,
    location: 'Chennai',
    language: 'SANSKRIT',
    package_type: 'PREMIUM',
    price: '11000.00',
    description: 'Premium Dhanvantari Puja with elaborate healing rituals, rare herbs, and complete setup',
    includes_materials: true,
    priest_count: 2,
    is_active: true,
    created_at: '2024-01-01',
    updated_at: '2024-01-01'
  },

  // Continue with similar patterns for remaining services 13-24...
  // Kuber Puja packages (Service 13)
  {
    id: 37,
    puja_service: 13,
    location: 'Mumbai',
    language: 'HINDI',
    package_type: 'BASIC',
    price: '3000.00',
    description: 'Basic Kuber Puja with essential wealth mantras and simple offerings',
    includes_materials: false,
    priest_count: 1,
    is_active: true,
    created_at: '2024-01-01',
    updated_at: '2024-01-01'
  },
  {
    id: 38,
    puja_service: 13,
    location: 'Mumbai',
    language: 'SANSKRIT',
    package_type: 'STANDARD',
    price: '5000.00',
    description: 'Standard Kuber Puja with enhanced prosperity rituals and quality materials',
    includes_materials: true,
    priest_count: 1,
    is_active: true,
    created_at: '2024-01-01',
    updated_at: '2024-01-01'
  },
  {
    id: 39,
    puja_service: 13,
    location: 'Mumbai',
    language: 'SANSKRIT',
    package_type: 'PREMIUM',
    price: '8500.00',
    description: 'Premium Kuber Puja with elaborate wealth rituals, gold offerings, and complete setup',
    includes_materials: true,
    priest_count: 2,
    is_active: true,
    created_at: '2024-01-01',
    updated_at: '2024-01-01'
  },

  // Adding packages for remaining services 14-24 (condensed for brevity)
  // Mangal Dosha Puja (14), Pitra Dosha Puja (15), Vastu Shanti (16), etc.
  // Each following the same pattern with 3 packages per service

  // Quick addition for services 14-24 with basic structure
  {
    id: 40,
    puja_service: 14,
    location: 'Gurgaon',
    language: 'SANSKRIT',
    package_type: 'BASIC',
    price: '5500.00',
    description: 'Basic Mangal Dosha Puja with essential marriage harmony rituals',
    includes_materials: false,
    priest_count: 1,
    is_active: true,
    created_at: '2024-01-01',
    updated_at: '2024-01-01'
  },
  {
    id: 41,
    puja_service: 14,
    location: 'Gurgaon',
    language: 'SANSKRIT',
    package_type: 'STANDARD',
    price: '8500.00',
    description: 'Standard Mangal Dosha Puja with enhanced compatibility rituals and quality materials',
    includes_materials: true,
    priest_count: 1,
    is_active: true,
    created_at: '2024-01-01',
    updated_at: '2024-01-01'
  },
  {
    id: 42,
    puja_service: 14,
    location: 'Gurgaon',
    language: 'SANSKRIT',
    package_type: 'PREMIUM',
    price: '13000.00',
    description: 'Premium Mangal Dosha Puja with elaborate marriage rituals, special offerings, and complete setup',
    includes_materials: true,
    priest_count: 2,
    is_active: true,
    created_at: '2024-01-01',
    updated_at: '2024-01-01'
  }
];

export const mockPujaServices: PujaService[] = [
  {
    id: 1,
    title: 'Ganesha Puja - Obstacle Remover',
    image: '/astrology_image/1719873166520-_fb9d8287-b465-4a48-a7b7-7659afd774c4.jpeg',
    image_thumbnail: '/astrology_image/1719873166520-_fb9d8287-b465-4a48-a7b7-7659afd774c4.jpeg',
    image_card: '/astrology_image/1719873166520-_fb9d8287-b465-4a48-a7b7-7659afd774c4.jpeg',
    description: 'Lord Ganesha is worshipped as the remover of obstacles and the patron of arts and sciences. This puja brings prosperity, wisdom, and success in all endeavors.',
    category: mockCategories[0],
    type: 'HOME',
    duration_minutes: 120,
    is_active: true,
    created_at: '2024-01-01',
    updated_at: '2024-01-01',
    packages: mockPackages.filter(p => p.puja_service === 1)
  },
  {
    id: 2,
    title: 'Lakshmi Puja - Wealth & Prosperity',
    image: '/astrology_image/1719873424564-kalash.jpg',
    image_thumbnail: '/astrology_image/1719873424564-kalash.jpg',
    image_card: '/astrology_image/1719873424564-kalash.jpg',
    description: 'Goddess Lakshmi puja is performed to attract wealth, prosperity, and abundance. This sacred ritual brings financial stability and material comforts.',
    category: mockCategories[1],
    type: 'HOME',
    duration_minutes: 90,
    is_active: true,
    created_at: '2024-01-01',
    updated_at: '2024-01-01',
    packages: mockPackages.filter(p => p.puja_service === 2)
  },
  {
    id: 3,
    title: 'Saraswati Puja - Knowledge & Wisdom',
    image: '/astrology_image/1719873508106-marriage.jpeg',
    image_thumbnail: '/astrology_image/1719873508106-marriage.jpeg',
    image_card: '/astrology_image/1719873508106-marriage.jpeg',
    description: 'Goddess Saraswati puja enhances knowledge, wisdom, and learning abilities. Perfect for students, artists, and knowledge seekers.',
    category: mockCategories[2],
    type: 'TEMPLE',
    duration_minutes: 75,
    is_active: true,
    created_at: '2024-01-01',
    updated_at: '2024-01-01',
    packages: mockPackages.filter(p => p.puja_service === 3)
  },
  {
    id: 4,
    title: 'Mahamrityunjaya Puja - Health & Protection',
    image: '/astrology_image/1719873855062-marriage.jpeg',
    image_thumbnail: '/astrology_image/1719873855062-marriage.jpeg',
    image_card: '/astrology_image/1719873855062-marriage.jpeg',
    description: 'This powerful Shiva puja provides protection from negative energies, promotes healing, and ensures long life and good health.',
    category: mockCategories[3],
    type: 'HOME',
    duration_minutes: 150,
    is_active: true,
    created_at: '2024-01-01',
    updated_at: '2024-01-01',
    packages: mockPackages.filter(p => p.puja_service === 4)
  },
  {
    id: 5,
    title: 'Durga Puja - Divine Protection',
    image: '/astrology_image/1719874036635-_bc717e95-309f-45ca-a716-ee76080d280b.jpeg',
    image_thumbnail: '/astrology_image/1719874036635-_bc717e95-309f-45ca-a716-ee76080d280b.jpeg',
    image_card: '/astrology_image/1719874036635-_bc717e95-309f-45ca-a716-ee76080d280b.jpeg',
    description: 'Goddess Durga puja offers divine protection from all evils and negativity. It empowers devotees with strength and courage.',
    category: mockCategories[4],
    type: 'TEMPLE',
    duration_minutes: 180,
    is_active: true,
    created_at: '2024-01-01',
    updated_at: '2024-01-01',
    packages: mockPackages.filter(p => p.puja_service === 5)
  },
  {
    id: 6,
    title: 'Navgraha Puja - Planetary Peace',
    image: '/astrology_image/1719874152890-_951f3e0d-7cfb-46be-a282-c54c5c4093f1.jpeg',
    image_thumbnail: '/astrology_image/1719874152890-_951f3e0d-7cfb-46be-a282-c54c5c4093f1.jpeg',
    image_card: '/astrology_image/1719874152890-_951f3e0d-7cfb-46be-a282-c54c5c4093f1.jpeg',
    description: 'Navgraha puja pacifies all nine planets and brings harmony in life. It reduces malefic effects and enhances positive planetary influences.',
    category: mockCategories[5],
    type: 'ONLINE',
    duration_minutes: 200,
    is_active: true,
    created_at: '2024-01-01',
    updated_at: '2024-01-01',
    packages: mockPackages.filter(p => p.puja_service === 6)
  },
  {
    id: 7,
    title: 'Satyanarayan Puja - Wish Fulfillment',
    image: '/astrology_image/1719949344992-Astrology Chart Reading.jpeg',
    image_thumbnail: '/astrology_image/1719949344992-Astrology Chart Reading.jpeg',
    image_card: '/astrology_image/1719949344992-Astrology Chart Reading.jpeg',
    description: 'Lord Vishnu\'s Satyanarayan puja fulfills desires and brings happiness, peace, and prosperity to the family.',
    category: mockCategories[6],
    type: 'HOME',
    duration_minutes: 135,
    is_active: true,
    created_at: '2024-01-01',
    updated_at: '2024-01-01',
    packages: mockPackages.filter(p => p.puja_service === 7)
  },
  {
    id: 8,
    title: 'Griha Pravesh Puja - New Home Blessing',
    image: '/astrology_image/1719949430249-Astrology Chart Reading.jpeg',
    image_thumbnail: '/astrology_image/1719949430249-Astrology Chart Reading.jpeg',
    image_card: '/astrology_image/1719949430249-Astrology Chart Reading.jpeg',
    description: 'Sacred ritual performed before entering a new home. It purifies the space and invites positive energies for a happy life.',
    category: mockCategories[7],
    type: 'HOME',
    duration_minutes: 90,
    is_active: true,
    created_at: '2024-01-01',
    updated_at: '2024-01-01',
    packages: mockPackages.filter(p => p.puja_service === 8)
  },
  {
    id: 9,
    title: 'Kaal Sarp Dosh Puja - Remedy Ritual',
    image: '/astrology_image/1719950441017-Astrology Chart Reading.jpeg',
    image_thumbnail: '/astrology_image/1719950441017-Astrology Chart Reading.jpeg',
    image_card: '/astrology_image/1719950441017-Astrology Chart Reading.jpeg',
    description: 'Special puja to neutralize Kaal Sarp Dosh effects. Brings relief from obstacles and promotes spiritual growth.',
    category: mockCategories[3],
    type: 'TEMPLE',
    duration_minutes: 240,
    is_active: true,
    created_at: '2024-01-01',
    updated_at: '2024-01-01',
    packages: mockPackages.filter(p => p.puja_service === 9)
  },
  {
    id: 10,
    title: 'Rudrabhishek Puja - Shiva Blessing',
    image: '/astrology_image/1719950490438-Astrology Chart Reading.jpeg',
    image_thumbnail: '/astrology_image/1719950490438-Astrology Chart Reading.jpeg',
    image_card: '/astrology_image/1719950490438-Astrology Chart Reading.jpeg',
    description: 'Sacred ablution of Lord Shiva for health, prosperity, and spiritual advancement. Removes negativity and grants peace.',
    category: mockCategories[3],
    type: 'HOME',
    duration_minutes: 105,
    is_active: true,
    created_at: '2024-01-01',
    updated_at: '2024-01-01',
    packages: mockPackages.filter(p => p.puja_service === 10)
  },
  
  // 14 New Puja Services
  {
    id: 11,
    title: 'Hanuman Puja - Strength & Courage',
    image: '/astrology_image/1719950838978-Astrology Chart Reading.jpeg',
    image_thumbnail: '/astrology_image/1719950838978-Astrology Chart Reading.jpeg',
    image_card: '/astrology_image/1719950838978-Astrology Chart Reading.jpeg',
    description: 'Lord Hanuman puja grants physical and mental strength, courage, and protection from evil forces. Ideal for overcoming challenges.',
    category: mockCategories[3],
    type: 'HOME',
    duration_minutes: 90,
    is_active: true,
    created_at: '2024-01-01',
    updated_at: '2024-01-01',
    packages: mockPackages.filter(p => p.puja_service === 11)
  },
  {
    id: 12,
    title: 'Dhanvantari Puja - Health & Healing',
    image: '/astrology_image/1720023693989-Birth Chart Analysis.jpeg',
    image_thumbnail: '/astrology_image/1720023693989-Birth Chart Analysis.jpeg',
    image_card: '/astrology_image/1720023693989-Birth Chart Analysis.jpeg',
    description: 'Lord Dhanvantari puja promotes healing, good health, and recovery from illness. The divine physician\'s blessings for wellness.',
    category: mockCategories[3],
    type: 'TEMPLE',
    duration_minutes: 120,
    is_active: true,
    created_at: '2024-01-01',
    updated_at: '2024-01-01',
    packages: mockPackages.filter(p => p.puja_service === 12)
  },
  {
    id: 13,
    title: 'Kuber Puja - Wealth Multiplication',
    image: '/astrology_image/1720023834619-Tarot Reading.jpeg',
    image_thumbnail: '/astrology_image/1720023834619-Tarot Reading.jpeg',
    image_card: '/astrology_image/1720023834619-Tarot Reading.jpeg',
    description: 'Lord Kuber puja attracts wealth, prosperity, and financial abundance. The treasurer of gods blesses with monetary gains.',
    category: mockCategories[1],
    type: 'HOME',
    duration_minutes: 75,
    is_active: true,
    created_at: '2024-01-01',
    updated_at: '2024-01-01',
    packages: mockPackages.filter(p => p.puja_service === 13)
  },
  {
    id: 14,
    title: 'Mangal Dosha Puja - Marriage Harmony',
    image: '/astrology_image/1720024001389-Tarot Reading.jpeg',
    image_thumbnail: '/astrology_image/1720024001389-Tarot Reading.jpeg',
    image_card: '/astrology_image/1720024001389-Tarot Reading.jpeg',
    description: 'Special puja to reduce Mangal Dosha effects and promote marital harmony, compatibility, and happiness in relationships.',
    category: mockCategories[5],
    type: 'TEMPLE',
    duration_minutes: 180,
    is_active: true,
    created_at: '2024-01-01',
    updated_at: '2024-01-01',
    packages: mockPackages.filter(p => p.puja_service === 14)
  },
  {
    id: 15,
    title: 'Pitra Dosha Puja - Ancestral Peace',
    image: '/astrology_image/1720024049302-Tarot Reading.jpeg',
    image_thumbnail: '/astrology_image/1720024049302-Tarot Reading.jpeg',
    image_card: '/astrology_image/1720024049302-Tarot Reading.jpeg',
    description: 'Pitra Dosha puja brings peace to ancestors and removes obstacles caused by ancestral displeasure. Promotes family harmony.',
    category: mockCategories[5],
    type: 'TEMPLE',
    duration_minutes: 210,
    is_active: true,
    created_at: '2024-01-01',
    updated_at: '2024-01-01',
    packages: mockPackages.filter(p => p.puja_service === 15)
  },
  {
    id: 16,
    title: 'Vastu Shanti Puja - Space Purification',
    image: '/astrology_image/1720024142095-Tarot Reading.jpeg',
    image_thumbnail: '/astrology_image/1720024142095-Tarot Reading.jpeg',
    image_card: '/astrology_image/1720024142095-Tarot Reading.jpeg',
    description: 'Vastu Shanti puja purifies and energizes living spaces according to Vastu principles. Brings harmony and positive energy.',
    category: mockCategories[7],
    type: 'HOME',
    duration_minutes: 150,
    is_active: true,
    created_at: '2024-01-01',
    updated_at: '2024-01-01',
    packages: mockPackages.filter(p => p.puja_service === 16)
  },
  {
    id: 17,
    title: 'Kali Puja - Divine Power',
    image: '/astrology_image/1720024596515-Tarot Reading.jpeg',
    image_thumbnail: '/astrology_image/1720024596515-Tarot Reading.jpeg',
    image_card: '/astrology_image/1720024596515-Tarot Reading.jpeg',
    description: 'Goddess Kali puja removes negative energies, provides protection from enemies, and grants divine power and fearlessness.',
    category: mockCategories[4],
    type: 'TEMPLE',
    duration_minutes: 165,
    is_active: true,
    created_at: '2024-01-01',
    updated_at: '2024-01-01',
    packages: mockPackages.filter(p => p.puja_service === 17)
  },
  {
    id: 18,
    title: 'Baglamukhi Puja - Victory & Protection',
    image: '/astrology_image/1720024869036-Palmistry.jpeg',
    image_thumbnail: '/astrology_image/1720024869036-Palmistry.jpeg',
    image_card: '/astrology_image/1720024869036-Palmistry.jpeg',
    description: 'Goddess Baglamukhi puja grants victory over enemies, protection from legal issues, and success in competitions.',
    category: mockCategories[4],
    type: 'TEMPLE',
    duration_minutes: 195,
    is_active: true,
    created_at: '2024-01-01',
    updated_at: '2024-01-01',
    packages: mockPackages.filter(p => p.puja_service === 18)
  },
  {
    id: 19,
    title: 'Surya Puja - Solar Energy',
    image: '/astrology_image/1720025006845-Numerology.jpeg',
    image_thumbnail: '/astrology_image/1720025006845-Numerology.jpeg',
    image_card: '/astrology_image/1720025006845-Numerology.jpeg',
    description: 'Lord Surya puja enhances vitality, leadership qualities, and success. Brings positive solar energy and removes darkness.',
    category: mockCategories[5],
    type: 'TEMPLE',
    duration_minutes: 135,
    is_active: true,
    created_at: '2024-01-01',
    updated_at: '2024-01-01',
    packages: mockPackages.filter(p => p.puja_service === 19)
  },
  {
    id: 20,
    title: 'Chandra Puja - Mental Peace',
    image: '/astrology_image/1720041573459-Vastu Shastra Consultation.jpeg',
    image_thumbnail: '/astrology_image/1720041573459-Vastu Shastra Consultation.jpeg',
    image_card: '/astrology_image/1720041573459-Vastu Shastra Consultation.jpeg',
    description: 'Lord Chandra puja brings mental peace, emotional stability, and enhances intuition. Ideal for reducing stress and anxiety.',
    category: mockCategories[5],
    type: 'HOME',
    duration_minutes: 90,
    is_active: true,
    created_at: '2024-01-01',
    updated_at: '2024-01-01',
    packages: mockPackages.filter(p => p.puja_service === 20)
  },
  {
    id: 21,
    title: 'Shani Puja - Saturn Pacification',
    image: '/astrology_image/1720041771232-Gemology.jpeg',
    image_thumbnail: '/astrology_image/1720041771232-Gemology.jpeg',
    image_card: '/astrology_image/1720041771232-Gemology.jpeg',
    description: 'Lord Shani puja reduces malefic effects of Saturn, brings justice, and removes obstacles. Essential for Saturn-related problems.',
    category: mockCategories[5],
    type: 'TEMPLE',
    duration_minutes: 225,
    is_active: true,
    created_at: '2024-01-01',
    updated_at: '2024-01-01',
    packages: mockPackages.filter(p => p.puja_service === 21)
  },
  {
    id: 22,
    title: 'Rahu-Ketu Puja - Karmic Cleansing',
    image: '/astrology_image/1720041883255-Feng Shui Advice.jpeg',
    image_thumbnail: '/astrology_image/1720041883255-Feng Shui Advice.jpeg',
    image_card: '/astrology_image/1720041883255-Feng Shui Advice.jpeg',
    description: 'Rahu-Ketu puja neutralizes shadow planet effects, clears karmic debts, and provides spiritual protection and growth.',
    category: mockCategories[5],
    type: 'TEMPLE',
    duration_minutes: 270,
    is_active: true,
    created_at: '2024-01-01',
    updated_at: '2024-01-01',
    packages: mockPackages.filter(p => p.puja_service === 22)
  },
  {
    id: 23,
    title: 'Santoshi Mata Puja - Happiness & Contentment',
    image: '/astrology_image/1720042000004-Psychic Reading.jpeg',
    image_thumbnail: '/astrology_image/1720042000004-Psychic Reading.jpeg',
    image_card: '/astrology_image/1720042000004-Psychic Reading.jpeg',
    description: 'Santoshi Mata puja brings happiness, contentment, and fulfills wishes. Special puja for family harmony and satisfaction.',
    category: mockCategories[4],
    type: 'HOME',
    duration_minutes: 105,
    is_active: true,
    created_at: '2024-01-01',
    updated_at: '2024-01-01',
    packages: mockPackages.filter(p => p.puja_service === 23)
  },
  {
    id: 24,
    title: 'Annapurna Puja - Food & Nourishment',
    image: '/astrology_image/1720042104329-Face Reading.jpeg',
    image_thumbnail: '/astrology_image/1720042104329-Face Reading.jpeg',
    image_card: '/astrology_image/1720042104329-Face Reading.jpeg',
    description: 'Goddess Annapurna puja ensures abundance of food, nourishment, and prosperity. Removes hunger and poverty from life.',
    category: mockCategories[1],
    type: 'HOME',
    duration_minutes: 120,
    is_active: true,
    created_at: '2024-01-01',
    updated_at: '2024-01-01',
    packages: mockPackages.filter(p => p.puja_service === 24)
  }
];

export const typeDisplayNames = {
  HOME: 'At Home',
  TEMPLE: 'At Temple', 
  ONLINE: 'Online'
};

export const languageDisplayNames = {
  HINDI: 'Hindi',
  ENGLISH: 'English',
  SANSKRIT: 'Sanskrit',
  REGIONAL: 'Regional'
};

export const packageTypeDisplayNames = {
  BASIC: 'Basic',
  STANDARD: 'Standard',
  PREMIUM: 'Premium',
  CUSTOM: 'Custom'
};
