name: Deploy to VPS

on:
  push:
    branches:
      - master  # or your deploy branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up SSH agent
      uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: ${{ secrets.VPS_SSH_KEY }}

    - name: Connect to VPS and pull latest changes
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} "
          cd ${{ secrets.VPS_PATH }} && \
          git pull origin master
        "

    - name: Install dependencies
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} "
          cd ${{ secrets.VPS_PATH }} && \
          pnpm install
        "

    - name: Build application
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} "
          cd ${{ secrets.VPS_PATH }} && \
          pnpm run build
        "

    - name: Restart application with PM2
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} "
          cd ${{ secrets.VPS_PATH }} && \
          pm2 restart okpuja
        "